### ISSUE TITLE
The frontend should call the suggestion endpoint instead of executing a search when typing the query

### ISSUE THREAD

**Issue by andraskalman** [k-monitor/parldata#21] opened 2019-02-16 20:11 UTC
Sometimes it is confusing when typing a query: search results are shown for the partial query phrase (which are absolutely not related with what I would like to search) then disappearing when typing a new character, then showing unrelated hits again after the next char and so on until the typing is finished.
For example: start typing `lázár`

It would be better if the suggestion API endpoint would be called and some meaningful suggestions would be shown for the user to choose one to spare typing.

Endpoint documentation: https://github.com/k-monitor/parldata/tree/master/src/elasticsearch 3.6

**Comment by andraskalman** [comment] 2019-02-16 20:14
This also renders access logs to be unusable, there are too much noise due to the searches during typing

**Comment by kantord** [comment] 2019-02-16 20:20
Duplicate of https://github.com/k-monitor/parliamentary_debates_open/issues/4

I plan to implement this eventually, but I would argue that it's not the most pressing issue right now.

> This also renders access logs to be unusable, there are too much noise due to the searches during typing

**Closed** 2019-02-16 20:23 UTC
